# Generated by Django 5.0.6 on 2026-06-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhao', 'Caminhão'), ('utilitario', 'Veículo Utilitário'), ('imovel', 'Imóvel'), ('loja', 'Loja / Ponto Comercial'), ('maquina', 'Máquina / Equipamento'), ('ti', 'Equipamento de TI'), ('moveis', 'Móveis / Utensílios'), ('estoque', 'Estoque / Mercadoria'), ('investimento', 'Investimento (Banco/Aplicação)'), ('participacao', 'Participação Societária'), ('outro', 'Outro')], max_length=20),
        ),
    ]
