# Generated by Django 5.0.6 on 2026-06-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('capacidade_carga', models.DecimalField(decimal_places=2, help_text='Toneladas', max_digits=8)),
                ('km_atual', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='empresa.empresa')),
            ],
            options={
                'ordering': ['placa'],
                'unique_together': {('empresa', 'placa')},
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('revisao', 'Revisão'), ('pneu', 'Pneu'), ('outro', 'Outro')], max_length=12)),
                ('descricao', models.CharField(max_length=500)),
                ('oficina', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_manutencao', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('proxima_revisao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota.veiculo')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('km_atual', models.PositiveIntegerField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posto', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='frota.veiculo')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
