# Generated by Django 5.0.6 on 2026-06-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(blank=True, max_length=200)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('saida', models.DateTimeField()),
                ('retorno', models.DateTimeField(blank=True, null=True)),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='frota.veiculo')),
            ],
            options={
                'ordering': ['-saida'],
            },
        ),
    ]
