# Generated by Django 5.0.6 on 2026-06-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_logo'),
        ('frota', '0002_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='Número CNH')),
                ('cnh_categoria', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, verbose_name='Categoria CNH')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas', to='empresa.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'cpf')},
            },
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='frota.motorista'),
        ),
    ]
