# Generated by Django 5.0.6 on 2026-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_motorista_alter_viagem_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada')], default='realizada', max_length=10),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='km_manutencao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
