# Generated by Django 5.0.6 on 2026-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_add_status_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='ajudante1_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ajudante 1 — Nome'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='ajudante1_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ajudante 1 — Telefone'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='ajudante2_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ajudante 2 — Nome'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='ajudante2_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ajudante 2 — Telefone'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='ajudante3_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ajudante 3 — Nome'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='ajudante3_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ajudante 3 — Telefone'),
        ),
    ]
