# Generated by Django 5.0.6 on 2026-06-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_add_ajudantes_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='frota.veiculo'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='frota.veiculo'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frota.veiculo'),
        ),
    ]
