# Generated by Django 5.0.6 on 2026-06-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('origem', models.CharField(max_length=200, verbose_name='Centro de Origem')),
                ('destino', models.CharField(max_length=200, verbose_name='Centro de Destino')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('aporte', 'Aporte'), ('repasse', 'Repasse')], max_length=10)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
