# Generated by Django 5.0.6 on 2026-06-05 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('centro_custo', models.CharField(max_length=200, verbose_name='Centro de Custo')),
                ('subgrupo', models.CharField(max_length=200, verbose_name='SubGrupo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Forma de Pagamento')),
                ('situacao', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
