# Generated by Django 5.0.6 on 2026-06-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('financeiro', '0003_centrocusto_formapagamento_subgrupo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subgrupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='repasse',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(max_length=200, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='subgrupo',
            unique_together={('empresa', 'nome')},
        ),
    ]
